### ISSUE TITLE
Wrong frontpage prompt placeholder.

### ISSUE THREAD

**Issue by iGormilhit** [rero/reroils-app#1]
The place holder of the front page is: What's in you mind?

It should be: What's in you**r** mind?

And maybe the whole expression isn't right or relevant in that context. See:
https://forum.wordreference.com/threads/whats-in-on-your-mind.2020132/

**Comment by pronguen** [comment]
Or rather "What do you have in mind?"
"'What is in your mind' is not a set phrase, not a collocation, nor a very common arrangement of words."
From: https://forum.wordreference.com/threads/whats-in-on-your-mind.2020132/

**Comment by mmo** [comment]
Je pense que "What's on your mind?" est ce qu'on souhaite.
"As if trying to convey, what is it that's busying your mind the most(top priority) at that particular time."

**Comment by iGormilhit** [comment]
Je suis pour la proposition de @mmo

**Comment by iGormilhit** [comment]
En accord avec @jma le placeholder est adjugé à "What's on your mind?".
