### ISSUE TITLE
Item's location PID is checked only after pressing the submit button

### ISSUE THREAD

**Issue by NicolasLabat** [rero/reroils-app#14]
Ideally, the location PID should be checked while editing the field "Location" letting the field color to be green or red according to the PID validity.

**Comment by pronguen** [comment]
See [US 516](https://tree.taiga.io/project/rero21-reroils/us/516) on Taiga

**Comment by iGormilhit** [comment]
The PID is already unique, the check should be done on the location's code.

See the same US 516
