### ISSUE TITLE
Wrong call number in the "on loan" tab of the patron profile

### ISSUE THREAD

**Issue by NicolasLabat** [rero/reroils-app#22]
When several items of the same document are requested of which one is on loan, the display of the requested items in the patron profile on the "on loan" tab have the call number of the already on loan item displayed in the "pending" tab.

**Comment by iGormilhit** [comment]
@NicolasLabat I have trouble to understand this, so it's difficult to reproduce.

**Comment by iGormilhit** [comment]
This is fixed in the next deployement.
