### ISSUE TITLE
Error when trying to edit items

### ISSUE THREAD

**Issue by BadrAly** [rero/reroils-app#26]
Select the "Edit" button  after displaying any item by item_id @ https://ils.test.rero.ch/items/1

You will receive the error "Error: Cannot retrieve the record (item)." after clicking "submit"

**Comment by iGormilhit** [comment]
I just tried, without any errors.
But are we supposed to have an item detailed view?

**Comment by BadrAly** [comment]
try to edit the item 10638 @ https://ils.test.rero.ch/items/10638

In this version the item detailed view is available , for the future, have no idea :-)

**Comment by iGormilhit** [comment]
I tried and succeeded. :smiley: 
This view shouldn't have the edit/delete button I think. I don't know why they are there.

**Comment by iGormilhit** [comment]
@BadrAly I think this is happening only when one edits the item from the `domain.tld/items/[pid]` page. Using the document full view to edit an item works without error.

Since we shouldn't have an item full view, should we actually solve this?

**Comment by iGormilhit** [comment]
Is fixed by https://github.com/rero/reroils-data/commit/908e65983a563de9ac45d92f5f8151ea5a6e58af
