### ISSUE TITLE
Translation of languages item selection no coherent

### ISSUE THREAD

**Issue by iGormilhit** [rero/reroils-app#33]
![capture_109](https://user-images.githubusercontent.com/1557213/40963814-c31c5542-68a9-11e8-9002-e1f1d76b42bb.png)

**Comment by NicolasLabat** [comment]
"Français", "Allemand" et "Italien" corrigés dans Transifex (débutent par une MAJ.)

**Comment by NicolasLabat** [comment]
Not fixed

**Comment by iGormilhit** [comment]
Fixed.
