### ISSUE TITLE
Display item status on item detailed view

### ISSUE THREAD

**Issue by pronguen** [rero/reroils-app#46]
The item status should be displayed in the item detailed view (for the librarian).

**Comment by BadrAly** [comment]
How to test:

Checkout into the branch.
(baa-#46-display-item-status)
https://github.com/rero/reroils-data/tree/baa-%2346-display-item-status

Run the test.
Visit any item detailed view and make sure the item status is there

**Comment by NicolasLabat** [comment]
Run-tests.sh to check :
lists of files in version control and sdist do not match!
missing from VCS:
  reroils_data/.ropeproject
  reroils_data/.ropeproject/config.py

**Comment by iGormilhit** [comment]
@NicolasLabat I think this directory is specific to your environment and that we already jumped into them before. They shouldn't be in the `git` index.
