### ISSUE TITLE
Executing "docker-compose run web ./populate.sh" reveals $VIRTUAL_ENV not set

### ISSUE THREAD

**Issue by kernie** [rero/reroils-app#7]
Hi,

I created a docker-compose.yml file as described in file INSTALL.rst and got it "up".

Then executing 
```
docker-compose run web ./populate.sh
```
lead to error messages indicating that the variable VIRTUAL_ENV in script populate.sh was not set. In consequence the initialization data was searched in /src/.... instead of /home/invenio/reroils/src/.... 

Maybe a 
```
source /home/invenio/reroils/bin/activate
```
must be placed in the script.

Going over with
```
docker-compose exec web bash
```
and executing 
```
./populate.sh
```
 works perfectly.

Maarten

**Comment by iGormilhit** [comment]
Hi @kernie , glad to see that someone got interested in our Invenio project!
After the connection to the container, did you have to activate the virtualenv? Or launching the `populate.sh` was enough?

**Comment by kernie** [comment]
When using the second approach I hadn't to activate. To my understanding, the virtualenv is activated in the bashrc. So, logging in activates the virtualenv.

I placed a little script like:
```
#!/bin/bash
echo $VIRTUAL_ENV
echo "done envi.sh"
```
into the reroils environment and executed:
```
docker-compose exec web ./envi.sh
```
which gives 
```

done envi.sh
```
However executing inside the ennvironment I get
```
./envi.sh 
/home/invenio/reroils
done envi.sh
```

Thanks,
Maarten

**Comment by jma** [comment]
Hello @kernie,

did you run `docker-compose up` and wait until it has been finished before running `docker-compose run web ./populate.sh`? Just to be sure.

Thanks.

**Comment by kernie** [comment]
At least for the example with the envi.sh script I'm absolutely sure that everything was settled and ready.

I can rerun it. 

Would a simple |docker-compose down && docker-compose up| be sufficient or is a "harder" reset necessary?

**Comment by jma** [comment]
You have to remove your local repository (`changeit` in your `docker-compose` file).
